# serverless.yml
service: lambda-selenium

package:
  artifact: build/libs/lambda-selenium-all.jar

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: java8
  memorySize: 1024
  timeout: 300
  versionFunctions: false

functions:
  'lambda-selenium-demo':
    handler: 'com.testing.lambda.LambdaTestHandler::handleRequest'
    name: lambda-selenium-function
    description: Lambda Selenium Demo Tests
